### ISSUE TITLE
actions[action] is not a function

### ISSUE THREAD

**Issue by flammensturm** [AidasPa/uts#1]
When i'm doing "npx @aidaspa/uts" i get `npx: installed 158 in 6.215s` and then "actions[action] is not a function", any info about that ? imma look into the code to see if there's any error but is this supposed to say that

**Comment by flammensturm** [comment]
Error on my side. Fixed.

**Comment by AidasPa** [comment]
Hey! Thanks for opening an issue!

There's no help command yet, hence the error it can't find the function when no args are provided
